#!/bin/bash
# Start ES, load the data and shut it down
echo 'Starting ES'
/docker-entrypoint.sh elasticsearch -p /tmp/pid &

echo 'Waiting for ES to start'
until curl --output /dev/null --silent --head --fail http://127.0.0.1:9200; do
    printf '.'
    sleep 5
done
echo "ES has started"

echo "Create Ingest Pipeline"
curl -s -XPUT 127.0.0.1:9200/_ingest/pipeline/pharmacies?pretty --data-binary @/usr/share/elasticsearch/tmp/data/scripts/pharmacy-processor.json

echo "Create Index Mappings"
curl -s -XPUT 127.0.0.1:9200/pharmacies?pretty --data-binary @/usr/share/elasticsearch/tmp/data/mapping/mapping.json

echo "Starting bulk data insert"
curl -s -XPOST 127.0.0.1:9200/_bulk?pipeline=pharmacies --data-binary @/usr/share/elasticsearch/tmp/data/output/gp-data-bulk-insert.json | jq '. | { errors: .errors, itemsProcessed: (.items | length), millisecondDuration: .took }'

echo "Finished bulk data insert"

echo "Shutting down ES"

pkill -F /tmp/pid
